### ISSUE TITLE
In the search results, group flowers by bed name and then by cultivar

### ISSUE THREAD

**Issue by lverns** [UMM-CSci-3601-S17/digital-display-garden-iteration-4-dorfner-v2#3]

**Comment by chen4709** [comment]
Currently, the sorting is a bit arbitrary. For instance, the search result for 'petunia' lists beds as (13 -> 1s -> 2n -> 2s -> 5 -> 6 -> 7 -> 9 -> LG). We need to discuss what would be the best ordering.
