### ISSUE TITLE
Export of visit timestamps of plants

### ISSUE THREAD

**Issue by ferri082** [UMM-CSci-3601-S17/digital-display-garden-iteration-4-dorfner-v2#6]

**Comment by lverns** [comment]
A couple of things that were mentioned in the customer meeting
- Times of day that people use the garden
- Times of season that people use the garden
- (not mentioned?) times of week that people use the garden

**Comment by lverns** [comment]
I've merged the code that implements this. 

Do we want any documentation for this feature? More precisely, do we want to do a little write up of how you can create cool/meaningful charts with these in Excel 2016 and what the numbers tell you? (To be fair, we don't have any such docs for any of the other tabs in the export sheet so maybe that should wait until cleanup week?)
